### ISSUE TITLE
FGCamera breaks walker

### ISSUE THREAD

**Issue by hbeni** [slawekmikula/flightgear-addon-fgcamera#10]
When switching on the walker, the camera will not switch to the walk view.

We should detect that walker is outside and switch to the walk view.

**Comment by slawekmikula** [comment]
Thanks, for testing and providing event patches ! I do not have right now enough time to fly FG and use it thoroughly. This issue I won't even though about it so very good of You :)

**Comment by hbeni** [comment]
Found it by accident while Testing :)
