### ISSUE TITLE
Keyboard mapping without overriding default aircraft controls

### ISSUE THREAD

**Issue by slawekmikula** [slawekmikula/flightgear-addon-fgcamera#12]
Move default keyboard controls to more sophisticated. Right now when enabling fgcamera you don't have ability to control aircarft via up/down/right/left keys. Move fgcamera modification buttons to eg. shift+up or enable it only when configuring camera views.

**Comment by slawekmikula** [comment]
@hbeni I've looked at the current keyboard bindings and changed in order to not get into default keys. Camera positioning is moved to ctrl+up/down ... mapping. ctrl+space to change yoke mode. 

Additionally i'll add info on the startup to display notice that keys 0-9 will be replaced by fgcamera (and option to 'do not show it again')

**Comment by hbeni** [comment]
Hi there, very good!
Wouldn’t ctrl+mumber also fit?

**Comment by slawekmikula** [comment]
Don't know. I thought this buttons are most used one and using joystick or any other controller + other controls it would be OK to not have to use eg CTRL+9 to switch to this view (have to use two hands)

**Comment by slawekmikula** [comment]
I'll leave it as is. I'll add startup information about mapping override for mouse and keys 0-9 (other ticket). Closing this issue.
