### ISSUE TITLE
Add startup info about keyboard 0-9 mappings

### ISSUE THREAD

**Issue by slawekmikula** [slawekmikula/flightgear-addon-fgcamera#13]
Add startup info (with option to disable it) about keybinding change and keys 0-9 with different usage

**Comment by hbeni** [comment]
Seems to be already implemented in `master`, just fogot to close the issue, or is something missing?

**Comment by slawekmikula** [comment]
@hbeni yes, but this ticket was about startup info. It was commited in last week with some other tweaks. It's right now implemented. Closing.
